# Version: 1.1
FROM liyancode/restjmeter:v0.1

MAINTAINER liyancode "liyan.code@gmail.com"

USER root

EXPOSE 9999

WORKDIR /opt/restjmeter/code/1.1/

ENTRYPOINT ["ruby"]
CMD ["app.rb","-o","0.0.0.0"]